apiVersion: apps/v1 
kind: Deployment
metadata:
  name: java-app-deploy
  labels: 
     app: java-app

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: java-app

  template:
    metadata:
      labels:
        app: java-app
    spec:
      imagePullSecrets:
      - name: nexus-regcred
      containers:
      - name: myapp
        image: 13.127.72.63:8082/java-app:15
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
